
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: groups.codebook.dev
spec:
  additionalPrinterColumns:
  - JSONPath: .status.numInstances
    description: Number of instances in group
    name: Instances
    type: integer
  - JSONPath: .status.numRunningInstances
    description: Number of running instances in group
    name: Running
    type: integer
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: codebook.dev
  names:
    kind: Group
    listKind: GroupList
    plural: groups
    singular: group
  scope: ""
  subresources: {}
  validation:
    openAPIV3Schema:
      description: Group is the Schema for the groups API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: GroupSpec defines the desired state of Group
          properties:
            image:
              type: string
            instances:
              items:
                type: string
              type: array
            maxRunSeconds:
              format: int64
              type: integer
            storageCapacity:
              type: string
            storageClass:
              type: string
          required:
          - image
          - instances
          - maxRunSeconds
          type: object
        status:
          description: GroupStatus defines the observed state of Group
          properties:
            instances:
              items:
                properties:
                  name:
                    type: string
                  status:
                    type: string
                required:
                - name
                - status
                type: object
              type: array
            numInstances:
              format: int64
              type: integer
            numRunningInstances:
              format: int64
              type: integer
          required:
          - numInstances
          - numRunningInstances
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
